name: ai-services

services:

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    restart: unless-stopped
    volumes:
      - ~/data/homeMongoAIData:/data/db

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: unless-stopped

